--AUTHORNAME:
  --CREATE DATE:
  --DESCRIPTION: RECIVED TYPE OF BOOK AND DELIVER THE TITILES

CREATE PROCEDURE GET_BOOKS_BY_TITLES
@TYPE CHAR(12)
AS
BEGIN
SET NOCOUNT ON
SELECT TITLE,PRICE,TYPE FROM titles
WHERE TYPE=@TYPE
END
GO
-- YOU SHOULD SELECT EXCUTE THE STORE PROCEDURE AND ENTER YOUR TYPE TO SEE THE RESULTS
